Minor cleanup.

diff --git a/shlisp b/shlisp
--- a/shlisp
+++ b/shlisp
@@ -92,7 +92,7 @@ while getopts ":hd" optchar; do
             echo "Usage: shlisp [-h] [-d] [FILE] ...
 
   -h     Show command line options
-  -d     Show internal backtrace upon errors
+  -d     Show internal information, such as a backtrace upon errors
 "
             exit
             ;;
@@ -117,9 +117,9 @@ collect () {
         fi
         ((aggregated += objects_collected))
     done
-    #if ((aggregated > 0)); then
-        #printf "Objects colleted : %i\n" $aggregated
-    #fi
+    if $_debug && ((aggregated > 0)); then
+        printf "(%i objects colleted)\n" $aggregated
+    fi
     IFS=" "
 }
 collect_object () {
@@ -208,18 +208,19 @@ collect_lambda_or_macro () {
 }
 _args_length () {
     # "retvar=$1" $object=$2
-    local retvar=$1 object=$2 a i=0
-    while consp $object; do
-        read a object <<< ${objects[$object]}
-        symbolp "$a" || { _set_error "$(_print "$a") is not a symbol"; return 1; }
+    local retvar=$1 object=$2 s tail i=0
+    tail=$object
+    while consp $tail; do
+        read s tail <<< ${objects[$tail]}
+        symbolp "$s" || { _set_error "$(_print "$s") is not a symbol"; return 1; }
         ((i++))
     done
-    if null $object; then
+    if null $tail; then
         eval $retvar="'== $i'"
-    elif symbolp $object; then
+    elif symbolp $tail; then
         eval $retvar="'>= $i'"
     else
-        _set_error "$(_print "$a") is not a symbol"; return 1
+        _set_error "$(_print "$object") is neither list, dotted list, or symbol"; return 1
     fi
 }
 create_lambda_or_macro () {
@@ -343,7 +344,7 @@ read_tokens () {
     elif [[ $token =~ ^[a-zA-Z^#.\!?_~\<\>=|/*+-]+ ]]; then
         eval $retvar=\"${TYPE_SYMBOL}$token\"
     else
-        _set_error "Token $token is not a valid object"; return 1
+        _set_error "token $token is not a valid object"; return 1
     fi
 }
 atom () {
@@ -397,11 +398,7 @@ _print () {
             ;;
     esac
 }
-print () {
-    # object=$1
-    _print $1
-    printf "\n"
-}
+print () { echo "$(_print $1)"; }
 functionp () {
     [[ ${1:0:1} == ${TYPE_BI_FUNCTION} || ${1:0:1} == ${TYPE_FUNCTION} ]]
 }
@@ -410,15 +407,6 @@ special () { [[ ${1:0:1} == ${TYPE_SPECIAL} ]]; }
 integerp () { [[ ${1:0:1} == ${TYPE_INT} ]]; }
 symbolp () {
     [[ ${1:0:1} == ${TYPE_SYMBOL} || ${1:0:1} == ${TYPE_GENSYMBOL} ]]
-}
-listp_w_type () {
-    # object=$1 [type=$2]
-    local cons=$1 type=$2 car
-    while consp $cons; do
-        read car cons <<< ${objects[$cons]}
-        [[ -z $type || ${car:0:1} == $type ]] || return 1
-    done
-    null $cons || return 1
 }
 listp () {
     # object=$1
@@ -942,7 +930,7 @@ fi
 
 if (($# > 0)); then
     for file in "${@}"; do
-        [[ -r $file ]] && repl < "$file" || echo "Could not read file $file"
+        [[ -r $file ]] && repl < "$file" || echo "*** COULD NOT READ FILE $file"
     done
 else
     repl
